global using NUnit.Framework;
global using LeetCodeSolutions.Solutions.Array.Easy;
global using LeetCodeSolutions.Solutions.LinkedList.Hard;
global using LeetCodeSolutions.Solutions.LinkedList.Easy;
global using LeetCodeSolutions.Shared.Model;
global using LeetCodeSolutions.Solutions.LinkedList.Medium;
global using LeetCodeSolutions.Solutions.Array.Medium;
global using LeetCodeSolutions.Solutions.Tree.Easy;
global using LeetCodeSolutions.Solutions.HashTable.Easy;
